version: '3.8'

services:
  db:
    container_name: nest_audio_pg
    image: postgres:15.4
    environment:
      - POSTGRES_PASSWORD=${DS_PASSWORD}
      - POSTGRES_DB=${DS_NAME}
    ports:
      - 5437:5432
    volumes:
      - postgresvolume:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - nest_audio-network
    env_file:
      - .env

  redis:
    container_name: nest_audio_redis
    image: redis:6-alpine
    ports:
      - 6375:6379
    volumes:
      - redisvolume:/data
    restart: unless-stopped
    networks:
      - nest_audio-network

  api:
    container_name: nest_audio_api
    ports:
      - ${APP_PORT}:${APP_PORT}
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - NODE_ENV=production
    volumes:
      - apilogsvolume:/public
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - nest_audio-network
    env_file:
      - .env

networks:
  nest_audio-network:
    driver: bridge

volumes:
  postgresvolume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/user/container-data/nest_audio/database/postgresql/data
  apilogsvolume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/user/container-data/nest_audio/public
  redisvolume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/user/container-data/nest_audio/redis/data
