name: docker-compose-actions-workflow
on: push
jobs:
  deploy:
    runs-on: nest-audio
    steps:
      - uses: actions/checkout@v2
      - name: setup variables
        run: |
          touch .env
          echo APP_PORT=${{ secrets.APP_PORT }} >> .env
          echo DS_HOST=${{ secrets.DS_HOST }} >> .env
          echo DS_PORT=${{ secrets.DS_PORT }} >> .env
          echo DS_USERNAME=${{ secrets.DS_USERNAME }} >> .env
          echo DS_PASSWORD=${{ secrets.DS_PASSWORD }} >> .env
          echo DS_NAME=${{ secrets.DS_NAME }} >> .env
          echo DS_SYNCHRONIZE=${{ secrets.DS_SYNCHRONIZE }} >> .env
          cat .env
      - name: Build the stack
        run: docker compose up -d
