name: docker-compose-actions-workflow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: nest-audio
    steps:
      - uses: actions/checkout@v2
      - name: setup variables
        run: |
          touch .env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env

          echo APP_PORT=${{ secrets.APP_PORT }} >> .env
          echo APP_FRONT_END_DOMAIN=${{ secrets.APP_FRONT_END_DOMAIN }} >> .env
          echo APP_TRACK_UPLOAD_LIMIT=${{ secrets.APP_TRACK_UPLOAD_LIMIT }} >> .env
          echo APP_ACCESS_TOKEN_SECRET=${{ secrets.APP_ACCESS_TOKEN_SECRET }} >> .env
          echo APP_ACCESS_TOKEN_EXP=${{ secrets.APP_ACCESS_TOKEN_EXP }} >> .env
          echo APP_REFRESH_TOKEN_SECRET=${{ secrets.APP_REFRESH_TOKEN_SECRET }} >> .env
          echo APP_REFRESH_TOKEN_EXP=${{ secrets.APP_REFRESH_TOKEN_EXP }} >> .env
          echo APP_COOKIE_DOMAIN=${{ secrets.APP_COOKIE_DOMAIN }} >> .env
          echo APP_TRACK_FOLDER=${{ secrets.APP_TRACK_FOLDER }} >> .env
          echo APP_TRACK_MINIMUM_BIT_RATE=${{ secrets.APP_TRACK_MINIMUM_BIT_RATE }} >> .env

          echo LOG_MONGO=${{ secrets.LOG_MONGO }} >> .env
          echo LOG_MONGO_COLLECTION=${{ secrets.LOG_MONGO_COLLECTION }} >> .env
          echo LOG_MONGO_URI=${{ secrets.LOG_MONGO_URI }} >> .env
          echo LOG_LOKI=${{ secrets.LOG_LOKI }} >> .env
          echo LOG_LOKI_URL=${{ secrets.LOG_LOKI_URL }} >> .env

          echo OAUTH_GOOGLE_ID=${{ secrets.OAUTH_GOOGLE_ID }} >> .env
          echo OAUTH_GOOGLE_SECRET=${{ secrets.OAUTH_GOOGLE_SECRET }} >> .env
          echo OAUTH_GOOGLE_CALLBACK_URL=${{ secrets.OAUTH_GOOGLE_CALLBACK_URL }} >> .env

          echo DS_HOST=${{ secrets.DS_HOST }} >> .env
          echo DS_PORT=${{ secrets.DS_PORT }} >> .env
          echo DS_USERNAME=${{ secrets.DS_USERNAME }} >> .env
          echo DS_PASSWORD=${{ secrets.DS_PASSWORD }} >> .env
          echo DS_NAME=${{ secrets.DS_NAME }} >> .env
          echo DS_SYNCHRONIZE=${{ secrets.DS_SYNCHRONIZE }} >> .env

          echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env
          echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env
          echo REDIS_TTL=${{ secrets.REDIS_TTL }} >> .env
          cat .env
      - name: build the stack
        run: docker compose build --no-cache
      - name: deploy the stack
        run: |
          docker compose down --remove-orphans
          docker compose up -d
      - name: clean up docker image
        run: |
          docker image prune
